// CopyButton.jsx — Poora review copy karta hai clipboard mein
// Developer directly GitHub PR pe paste kar sakta hai

import { useState } from 'react';

const CopyButton = ({ review, prUrl }) => {
  const [copied, setCopied] = useState(false);

  const formatReview = () => {
    // Review ko readable text mein convert karo
    let text = '';

    text += `🤖 AI CODE REVIEW REPORT\n`;
    text += `${'='.repeat(50)}\n`;
    text += `📎 PR: ${prUrl}\n`;
    text += `📊 Quality Score: ${review.score}/100\n`;
    text += `🕐 Reviewed at: ${new Date().toLocaleString()}\n`;
    text += `${'='.repeat(50)}\n\n`;

    // Summary
    text += `📋 SUMMARY\n`;
    text += `${'-'.repeat(30)}\n`;
    text += `${review.summary}\n\n`;

    // Bugs
    text += `🔴 BUGS FOUND (${review.bugs?.length || 0})\n`;
    text += `${'-'.repeat(30)}\n`;
    if (review.bugs?.length > 0) {
      review.bugs.forEach((bug, i) => {
        text += `${i + 1}. File: ${bug.file} | Line: ${bug.line || 'N/A'}\n`;
        text += `   Issue: ${bug.issue}\n`;
        text += `   Fix: ${bug.fix}\n\n`;
      });
    } else {
      text += `✅ No bugs found!\n\n`;
    }

    // Security
    text += `🟠 SECURITY ISSUES (${review.security?.length || 0})\n`;
    text += `${'-'.repeat(30)}\n`;
    if (review.security?.length > 0) {
      review.security.forEach((sec, i) => {
        text += `${i + 1}. File: ${sec.file}\n`;
        text += `   Issue: ${sec.issue}\n`;
        text += `   Fix: ${sec.fix}\n\n`;
      });
    } else {
      text += `✅ No security issues found!\n\n`;
    }

    // Performance
    text += `🟡 PERFORMANCE ISSUES (${review.performance?.length || 0})\n`;
    text += `${'-'.repeat(30)}\n`;
    if (review.performance?.length > 0) {
      review.performance.forEach((perf, i) => {
        text += `${i + 1}. File: ${perf.file}\n`;
        text += `   Issue: ${perf.issue}\n`;
        text += `   Fix: ${perf.fix}\n\n`;
      });
    } else {
      text += `✅ No performance issues found!\n\n`;
    }

    // Suggestions
    text += `🟢 SUGGESTIONS (${review.suggestions?.length || 0})\n`;
    text += `${'-'.repeat(30)}\n`;
    if (review.suggestions?.length > 0) {
      review.suggestions.forEach((sug, i) => {
        text += `${i + 1}. File: ${sug.file}\n`;
        text += `   Issue: ${sug.issue}\n`;
        text += `   Fix: ${sug.fix}\n\n`;
      });
    } else {
      text += `✅ No suggestions!\n\n`;
    }

    text += `${'='.repeat(50)}\n`;
    text += `Generated by AI Code Reviewer 🤖\n`;
    text += `https://github.com/AnkurApex/Ai-Code-Reviewer-\n`;

    return text;
  };

  const handleCopy = async () => {
    try {
      const formattedText = formatReview();
      await navigator.clipboard.writeText(formattedText);
      setCopied(true);

      // 2 second baad wapas original text
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      alert('Copy failed — manually select karo');
    }
  };

  return (
    <button
      onClick={handleCopy}
      style={{
        padding: '10px 22px',
        background: copied ? '#00d4aa' : '#0f3460',
        color: '#ffffff',
        border: `1px solid ${copied ? '#00d4aa' : '#a8b2d8'}`,
        borderRadius: '8px',
        fontSize: '0.9rem',
        fontWeight: 'bold',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        display: 'flex',
        alignItems: 'center',
        gap: '8px'
      }}
    >
      {copied ? '✅ Copied!' : '📋 Copy Review'}
    </button>
  );
};

export default CopyButton;
